<a href="https://colab.research.google.com/github/SadiaSharmin/Python/blob/main/NumpyLibrary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



1. Numpy : large multi-dimensional array and matrix processing
2. Pandas :  data analysis
3. Matplotlib: visualization 
4. Scikit-learn
5. Scipy
6. TensorFlow
7. Keras
8. PyTorch


In [ ]:
import numpy as np

#NumPy is a Python library used for working with arrays. NumPy is short for "Numerical Python".
#NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
a0 = np.array(23)
print(a0)
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
a2 = np.array([[1, 2, 3,5],[4, 5, 6, 8]])
print(a2)

print(a2.ndim)
print(a2[1,0])
print(a2[1,-1])
#[start:end:step].
print(a2[1,0:2])
print(a2[1,::3])

print(a2.dtype)



23
[1 2 3 4 5]
[[1 2 3 5]
 [4 5 6 8]]
2
4
8
[4 5]
[4 8]
int64
(2, 4)


In [ ]:


#NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

print(a2.shape)

#Reshaping means changing the shape of an array.
#The shape of an array is the number of elements in each dimension.
#By reshaping we can add or remove dimensions or change number of elements in each dimension.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)
print(newarr)
newarr1 = arr.reshape(2, 3, 2)
print(newarr1)

#Flattening the arrays
#Flattening array means converting a multidimensional array into a 1D array.

#We can use reshape(-1) to do this.


newarr3 = newarr1.reshape(-1)

print(newarr3)

(2, 4)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#The numpy.zeros() function returns a new array of given shape and type, with zeros.
rows, cols = 3,4
array = np.zeros([3,3])
array2 = np.zeros([rows,cols])
print(array2)

array3 = np.ones([rows,cols])
print(array3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
x = np.random.rand(2,5)
print(x)

y = np.random.randint(1,20, size = (3,3))
print(y)

z = np.random.randn(2,5)
print(z)


a = np.eye(5)
a1 = np.eye(2, 3)
print(a1)

[[0.88656701 0.30611416 0.60336081 0.11209687 0.21067337]
 [0.3782115  0.56095355 0.24049271 0.19554221 0.17047432]]
[[ 7  1  6]
 [ 5 11 11]
 [ 3  4 11]]
[[-0.08223754  0.05795917  2.28172561  0.95578492  0.72823943]
 [ 0.32538493  0.49667165 -1.35487804  0.24342612 -0.93798146]]
[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
a = [1,2,3]
b = [3,5,6]

x = np.hstack((a,b))
print(x)

[1 2 3 3 5 6]
